# Chirpy site configuration
theme: jekyll-theme-chirpy

lang: zh-CN
timezone: Asia/Shanghai

title: YangGroup@HFNL
tagline: HPC 集群使用文档
description: >-
  YangGroup@HFNL HPC 集群使用文档。
url: "https://hfnl-yanggroup.github.io"
baseurl: ""

github:
  username: hfnl-yanggroup

social:
  name: YangGroup@HFNL
  links: []

avatar: /assets/images/ustc_logo.svg
theme_mode:
toc: true

actions:
  edit_post:
    enabled: true
    url: "https://github.com/hfnl-yanggroup/hfnl-yanggroup.github.io/edit/main"
    static_url: false

comments:
  provider:

paginate: 10

plugins:
  - jekyll-archives

# Generate the pages targeted by Chirpy's category and tag links.
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

pwa:
  enabled: true
  cache:
    enabled: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /:categories/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - ".backup"
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - "package*.json"
